spring:
  datasource:
    username: lostred
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/db01
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: embedded
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: embedded

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
